name: flutter_tdd
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_keyboard_visibility: ^5.4.0
  liquid_pull_to_refresh: ^3.0.1
  cached_network_image: ^3.2.3
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  image_picker: ^0.8.7+5
  equatable: ^2.0.5
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  tf_dio_cache: ^1.0.1
  fluttertoast: ^8.1.3
  shared_preferences: ^2.0.17
  auto_route: ^5.0.4
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.1.0
  firebase_messaging: ^14.2.2
  firebase_core: ^2.5.0
  flutter_local_notifications: ^13.0.0
  flutter_phoenix: ^1.1.0
  animations: ^2.0.7
  google_fonts: ^4.0.3
  pin_code_fields: ^7.4.0
  url_launcher: ^6.1.9
  flutter_launcher_icons: ^0.11.0
  path_provider: ^2.0.12
  permission_handler: ^10.2.0
  file_picker: ^5.2.5
  flutter_svg: ^2.0.0+1
  smooth_page_indicator: ^1.0.0+2
  country_calling_code_picker: ^2.0.1
  flutter_slidable: ^2.0.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  firebase_analytics: ^10.1.1
  firebase_crashlytics: ^3.0.12
  google_maps_flutter: ^2.2.3
  geocode: ^1.0.2
  new_version: ^0.3.1
  rate_my_app: ^1.1.3
  shimmer: ^3.0.0
  intl: ^0.17.0
  flutter_screenutil: ^5.6.1
  internet_connectivity_checker: ^0.1.0
  simple_connection_checker: ^0.2.1
  adaptive_theme: ^3.1.1
  widget_and_text_animator: ^1.0.9
  animated_bottom_navigation_bar: ^1.1.0
  card_swiper: ^2.0.4
  flutter_rating_bar: ^4.0.1
  flutter_bounce: ^1.1.0
  flutter_staggered_grid_view: ^0.6.2
  syncfusion_flutter_datepicker: ^20.4.49
  flutter_rounded_date_picker: ^3.0.2
  infinite_scroll_pagination: ^3.2.0
  lottie: ^2.3.2
  flutter_html:
  drift: ^2.8.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.2
  flutter_sticky_header: ^0.6.5
  scrollable_list_tab_scroller: ^1.1.0
  mac_address: ^1.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.8.0
  build_runner: ^2.3.3
  auto_route_generator: ^5.0.3
  injectable_generator: ^2.1.3
  flutter_lints: ^2.0.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/anims/animation_lkb5jn5s.json
    - assets/fonts/NotoSans.ttf
    - assets/images/apple.svg
    - assets/images/appLoaderBg.png
    - assets/images/arrow.svg
    - assets/images/blog.png
    - assets/images/emptyCart.png
    - assets/images/facebook.svg
    - assets/images/icon.png
    - assets/images/logo.png
    - assets/images/logoSvg.svg
    - assets/images/marker.png
    - assets/images/mobile.svg
    - assets/images/myProfile.png
    - assets/images/noData.png
    - assets/images/offline.png
    - assets/images/password.svg
    - assets/images/pdf.png
    - assets/images/profile.png
    - assets/images/suliitLogo.png
    - assets/lang/ar.json
    - assets/lang/en.json
  fonts:
    - family: NotoSans
      fonts:
       - asset: assets/fonts/NotoSans.ttf

