import 'package:flutter/material.dart';
import 'package:flutter_tdd/core/widgets/DefaultButton.dart';
import 'package:flutter_tdd/core/widgets/custom_dropDown/CustomDropDown.dart';
import 'package:flutter_tdd/core/widgets/default_app_bar.dart';
import 'package:flutter_tdd/features/base/data/models/drop_down_model/drop_down_model.dart';
import 'package:flutter_tdd/features/base/presentation/pages/add_new_address/widgets/add_new_address_widgets_imports.dart';
import 'package:flutter_tdd/features/general/presentation/pages/location_address/location_cubit/location_cubit.dart';
part 'add_new_address.dart';
part 'add_new_address_controller.dart';